<html>
<head>
<title>Compendium Search Helper</title>
<link href="icon.png" rel="apple-touch-icon" /> 
<!-- source: http://openclipart.org/people/ClayDowling/ClayDowling_D20.png -->
<link rel="stylesheet" href="styles.css" type="text/css" media="screen" /> 
<link media="only screen and (max-device-width: 480px)" href="iphone.css" type= "text/css" rel="stylesheet" />
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
</head>
<body>
